# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62e68225eb57d061c52877f92fa048fe91d5405660ad139a6eae21f4f32ae3a247f5fe11de8220fe72d6cb214a29771119fbb647f06f6a9c5382f33951188f38

test:
  secret_key_base: 03d4f5fd44256ea03a5fe166a8fb496d98593800d76411972f74c82f65fefefda1327e4ff84e0dd50e80a21c854d7b264cb1790dfa81c5688cdc26295c7b4037

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
